name: Git command

on:
  push:
    branches: [ main ]

jobs:
  git-info:
    runs-on: ubuntu-latest
    steps:
      - run: id
      - run: git config -l
      - uses: actions/checkout@v3
      - run: ls -al

  git-ok:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: git config --global --add safe.directory '*'
      - run: git log -n1

  git-fail:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: git log -n1
